# Generated by Django 5.0.1 on 2025-06-04 06:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location_type', models.CharField(choices=[('gym', '헬스장'), ('yoga', '요가원'), ('pilates', '필라테스'), ('crossfit', '크로스핏'), ('swimming', '수영장'), ('martial_arts', '무술도장'), ('dance', '댄스학원'), ('other', '기타')], max_length=20)),
                ('address', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('operating_hours', models.JSONField(default=dict, help_text='운영 시간')),
                ('rating', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '운동 장소',
                'verbose_name_plural': '운동 장소들',
                'db_table': 'exercise_locations',
            },
        ),
        migrations.CreateModel(
            name='MusicRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('artist', models.CharField(max_length=100)),
                ('album', models.CharField(blank=True, max_length=200)),
                ('spotify_id', models.CharField(blank=True, max_length=50)),
                ('preview_url', models.URLField(blank=True)),
                ('workout_type', models.CharField(choices=[('cardio', '유산소'), ('strength', '근력운동'), ('yoga', '요가'), ('stretching', '스트레칭'), ('hiit', 'HIIT'), ('running', '러닝')], max_length=20)),
                ('bpm', models.IntegerField(blank=True, help_text='Beats per minute', null=True)),
                ('energy_level', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '음악 추천',
                'verbose_name_plural': '음악 추천들',
                'db_table': 'music_recommendations',
            },
        ),
        migrations.CreateModel(
            name='WorkoutCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='아이콘 클래스명', max_length=50)),
            ],
            options={
                'verbose_name': '운동 카테고리',
                'verbose_name_plural': '운동 카테고리들',
                'db_table': 'workout_categories',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자들',
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', '사용자'), ('bot', '챗봇')], max_length=10)),
                ('message', models.TextField()),
                ('context', models.JSONField(blank=True, help_text='대화 컨텍스트', null=True)),
                ('embedding', models.JSONField(blank=True, help_text='메시지 임베딩', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '챗봇 메시지',
                'verbose_name_plural': '챗봇 메시지들',
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(120)])),
                ('height', models.FloatField(help_text='cm 단위', validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(300)])),
                ('weight', models.FloatField(help_text='kg 단위', validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(500)])),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], default='O', max_length=1)),
                ('exercise_experience', models.CharField(choices=[('beginner', '초급자 (1년 미만)'), ('intermediate', '중급자 (1-3년)'), ('advanced', '상급자 (3-5년)'), ('expert', '전문가 (5년 이상)')], default='beginner', max_length=20)),
                ('diseases', models.JSONField(default=list, help_text='질병 목록')),
                ('allergies', models.JSONField(default=list, help_text='알레르기 목록')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 프로필',
                'verbose_name_plural': '사용자 프로필들',
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='WorkoutVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('thumbnail_url', models.URLField()),
                ('duration', models.IntegerField(help_text='초 단위')),
                ('difficulty', models.CharField(choices=[('beginner', '초급'), ('intermediate', '중급'), ('advanced', '상급')], max_length=20)),
                ('target_muscles', models.JSONField(default=list, help_text='타겟 근육 목록')),
                ('view_count', models.IntegerField(default=0)),
                ('like_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.workoutcategory')),
            ],
            options={
                'verbose_name': '운동 영상',
                'verbose_name_plural': '운동 영상들',
                'db_table': 'workout_videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkoutLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration', models.IntegerField(help_text='분 단위')),
                ('calories_burned', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('workout_name', models.CharField(max_length=100)),
                ('sets', models.IntegerField(blank=True, null=True)),
                ('reps', models.IntegerField(blank=True, null=True)),
                ('weight', models.FloatField(blank=True, help_text='kg 단위', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_logs', to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.workoutvideo')),
            ],
            options={
                'verbose_name': '운동 기록',
                'verbose_name_plural': '운동 기록들',
                'db_table': 'workout_logs',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DietLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('meal_type', models.CharField(choices=[('breakfast', '아침'), ('lunch', '점심'), ('dinner', '저녁'), ('snack', '간식')], max_length=20)),
                ('food_items', models.JSONField(default=list, help_text='음식 항목 목록')),
                ('total_calories', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('protein', models.FloatField(blank=True, help_text='단백질(g)', null=True)),
                ('carbohydrates', models.FloatField(blank=True, help_text='탄수화물(g)', null=True)),
                ('fat', models.FloatField(blank=True, help_text='지방(g)', null=True)),
                ('fiber', models.FloatField(blank=True, help_text='식이섬유(g)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '식단 기록',
                'verbose_name_plural': '식단 기록들',
                'db_table': 'diet_logs',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date', 'meal_type')},
            },
        ),
    ]
