# Generated by Django 5.0.1 on 2025-06-05 01:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='disliked_exercises',
            field=models.JSONField(default=list, help_text='싫어하는 운동 목록'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disliked_foods',
            field=models.JSONField(default=list, help_text='싫어하는 음식 목록'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_exercises',
            field=models.JSONField(default=list, help_text='선호하는 운동 목록'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferred_foods',
            field=models.JSONField(default=list, help_text='선호하는 음식 목록'),
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('summary', models.TextField(blank=True, help_text='세션 대화 요약')),
                ('extracted_preferences', models.JSONField(default=dict, help_text='추출된 선호도 정보')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '챗봇 세션',
                'verbose_name_plural': '챗봇 세션들',
                'db_table': 'chat_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession'),
        ),
        migrations.CreateModel(
            name='VectorizedChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessions', models.JSONField(default=list, help_text='벡터화된 세션 ID 목록')),
                ('embedding', models.JSONField(help_text='대화 내용의 통합 임베딩')),
                ('summary', models.TextField(help_text='대화 내용 요약')),
                ('message_count', models.IntegerField(help_text='벡터화된 메시지 수')),
                ('date_range_start', models.DateTimeField(help_text='가장 오래된 메시지 시간')),
                ('date_range_end', models.DateTimeField(help_text='가장 최근 메시지 시간')),
                ('topics', models.JSONField(default=list, help_text='대화 주제들')),
                ('preferences', models.JSONField(default=dict, help_text='추출된 선호도 정보')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vectorized_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '벡터화된 대화 기록',
                'verbose_name_plural': '벡터화된 대화 기록들',
                'db_table': 'vectorized_chat_history',
                'ordering': ['-date_range_end'],
            },
        ),
        migrations.CreateModel(
            name='DailyRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('workout', '운동'), ('diet', '식단')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('details', models.JSONField(help_text='추천 상세 정보')),
                ('reasoning', models.TextField(help_text='추천 이유')),
                ('based_on', models.JSONField(default=dict, help_text='추천 근거 데이터')),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일일 추천',
                'verbose_name_plural': '일일 추천들',
                'db_table': 'daily_recommendations',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date', 'type')},
            },
        ),
    ]
