# Generated by Django 5.2 on 2025-06-10 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='user_session_number',
            field=models.IntegerField(default=1, help_text='사용자별 세션 번호'),
        ),
    ]
