# Generated by Django 5.2 on 2025-06-10 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_userprofile_custom_goal_userprofile_daily_steps_goal_and_more'),
    ]

    operations = [
    ]
