# Generated by Django 5.2 on 2025-06-10 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_add_map_music_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('workout_reminder', '운동 알림'), ('goal_achievement', '목표 달성'), ('social_activity', '친구 활동'), ('weekly_summary', '주간 요약')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('sent', '전송됨'), ('failed', '전송 실패'), ('pending', '대기중')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('fcm_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('fcm_response', models.JSONField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림 기록',
                'verbose_name_plural': '알림 기록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('fcm_token_updated_at', models.DateTimeField(auto_now=True)),
                ('enable_workout_reminders', models.BooleanField(default=True)),
                ('enable_goal_achievement_notif', models.BooleanField(default=True)),
                ('enable_social_activity_notif', models.BooleanField(default=True)),
                ('enable_weekly_summary', models.BooleanField(default=True)),
                ('reminder_time', models.TimeField(default='09:00', help_text='운동 알림을 받을 시간')),
                ('reminder_days', models.CharField(default='1,2,3,4,5', help_text='알림을 받을 요일 (0=일요일, 6=토요일)', max_length=20)),
                ('quiet_hours_start', models.TimeField(default='22:00', help_text='알림을 받지 않을 시간 시작')),
                ('quiet_hours_end', models.TimeField(default='07:00', help_text='알림을 받지 않을 시간 종료')),
                ('notification_language', models.CharField(choices=[('ko', '한국어'), ('en', 'English')], default='ko', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '알림 설정',
                'verbose_name_plural': '알림 설정',
            },
        ),
    ]
